### ISSUE TITLE
don't include credit line if there's no such data

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/DMA#1]
http://data.americanartcollaborative.org/page/dma/object/3041171/credit doesn't have any useful payload

**Comment by bmacelhose** [comment]
What exactly is credit line referencing here, the credit line for the acquisition of the artwork or the credit line for the image rights?

**Comment by bsnikhila** [comment]
@VladimirAlexiev  Fixed it.
@bmacelhose The credit line for the acquisition of the artwork
