### ISSUE TITLE
Many items do not have a Production

### ISSUE THREAD

**Issue by workergnome** [american-art/DMA#11]
see http://data.americanartcollaborative.org/page/dma/object/3273743.

There is no production information associated with this object, though there are details about it on Dallas's website.

**Comment by bsnikhila** [comment]
There is no production data provided for this object in the data file.

**Comment by workergnome** [comment]
Well, then there's not a lot you can do.  @bmacelhose, can you confirm that this data is not intended to  be published?

**Comment by bmacelhose** [comment]
"production information associated with this object" what does this mean?

What data are you referencing with respect to publishing?

**Comment by workergnome** [comment]
Sorry—

There is no Creator, Creation Date, or Creation Location associated with this work. 

I don't believe that y'all have been providing creation location, but most of your work has a creation date and a creator.   If you can double-check if this one was supposed to, we can figure out where the data went missing, or if it's by intent.

**Comment by bmacelhose** [comment]
The one that is referenced here has a creator associated with it, as you can see on our website. 

But, there should be about 29 objects that do not have a creator attributed to them. These are the object record IDs.

5342487
3176802
4097024
4228903
5336892
4164344
4201665
4232996
4244088
4090132
5342486
3067854
4313218
5333312
4164334
5235074
4119248
4021111
5342485
5342484
5326935
5331522
3202820
3064429
3102482
3085763
3167498
3049760
3269689

The creation date of the object may not be know but "n.d." should be there always. 

Correct, we did not supply geographical information.

**Comment by workergnome** [comment]
OK—the intent is to publish that information.

In the source data, the Artist information appears to be there, and the production, while the dates are null (or 0), has a label.

ObjectID | ClassificationObject | Copyright | CreditLine | CurrentLocation | DataDateStamp | DateBegin | Dated | DateEnd | Department | Edition | Inscription | ObjectOwned | ObjectNumber | PublicDescription | ResourceURL | Medium | DimensionsDisplayText | ConstituentBeginDate | BirthDeathDisplayDate | Nationality | CreatorDispOrder | ConstituentEndDate | DisplayName | FirstName | Gender | Institution | LastName | MiddleName | Role | Title | ImageURL | Label image | Image Display Order
-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-|-
3273743 | Drawings | Under review |  | storage | 2016-02-25T05:53:41.586000 | 0 | n.d. | 0 | American |  |  | Dallas Museum of Art | 1956.59 |  | https://www.dma.org/object/artwork/3273743/ | Pen and ink |  | 1905 |  | American | 1 | 0 | Peter Takal |  | male |  |  |  | Artist | Window in Brooklyn | http://files.dma.org/multimedia/images/266053271788461_thumbnail.jpg | Main Image | 1

**Comment by bmacelhose** [comment]
so we are all good now?

**Comment by workergnome** [comment]
@bmacelhose — you're good.  I understand what you're providing, and what your intent is.  

@bsnikhila — can you see why that artist is missing?

**Comment by bsnikhila** [comment]
Should be fixed.

**Comment by kateblanch** [comment]
Production event is present at http://data.americanartcollaborative.org/page/dma/object/3273743.
