### ISSUE TITLE
DMA actors (don't use blank nodes)

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/DMA#2]
http://data.americanartcollaborative.org/page/dma/object/3041171 has P62_depicts that leads to a blank node with no data: http://data.americanartcollaborative.org/pathpage/crm:P62_depicts/dma/object/3041171

Don't ever use blank nodes. Eg  use
- dma/object/3041171/depicted, or 
- dma/object/3041171/depicted/N if there are several

**Comment by bmacelhose** [comment]
Is this referencing the fact that there is no data related to the individual who have been named in the title of the artwork and presumably is also the sitter (aka depicted individual)?

**Comment by bsnikhila** [comment]
@bmacelhose There was an issue with the mapping, not with the data.

I'm not sure why there was an issue. But I have removed the 'Depicted' field for now as there was only one constituent in the role of Subject. I will add it back once we find the issue and correct it.

**Comment by VladimirAlexiev** [comment]
The DMA data has 2 duplicate files: `Constituents/Dallas Museum of Art - LOD - UPDATED.csv` and `Objects/Dallas Museum of Art - LOD - UPDATED.csv`.  These are badly denormalized since each row describes BOTH an object and a constituent. 

You need to find the cols that describe a constituent, and convert that to an Actor (or Person or Group, if you can tell what it is). I think these are the cols, but some of them are empty:
- ConstituentBeginDate | BirthDeathDisplayDate | Nationality | CreatorDispOrder | ConstituentEndDate | DisplayName | FirstName | Gender | Institution | LastName | MiddleName | Role

You also need to decide on a constituent URL because I don't see a constituent ID: I think you should use DisplayName to make a URL.

Most DMA objects have Role=Artist. The exceptions are:
- 4185726 title="Virgin of the Immaculate Heart". Depicted individual: Mary , Nationality=Judean
- 4326693 Engraver: Timothy Cole (and 3-4 more with the same role)

According to [Actor mapping](http://review.americanartcollaborative.org/entity/E39_Actor) eg for the first one you should emit:
```ttl
<object/4185726> P62_depicts <constituent/Mary>.
<constituent/Mary> a E39_Actor;
  # skip birth/death=0 because that means no data
  rdfs:label "Mary";
  P131_is_identified_by <constituent/Mary/appellation>;
  P107i_is_current_or_former_member_of <nationality/Judean>.
<constituent/Mary/appellation> a E82_Actor_Appellation;
  rdf:value "Mary";
  P2_has_type aat:300404670. # preferred name
<nationality/Judean> a E74_Group;
  rdfs:label "Judean";
  P2_has_type aat:300379842. # nationality
```

**Comment by bsnikhila** [comment]
Fixed.
