### ISSUE TITLE
remove aat:300404670 from Description

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/DMA#3]
http://data.americanartcollaborative.org/page/dma/object/3041171/description has 2 AAT concepts:
- aat:300080091 "description" is right.
- aat:300404670 "preferred terms" is not relevant, so remove it

**Comment by bsnikhila** [comment]
The [mapping](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_7-search_0) shows both aat terms. It won't work without both I believe.

**Comment by workergnome** [comment]
We have both because some institutions have multiple descriptions, and have chosen one to be the preferred description.
