### ISSUE TITLE
DMA material thesaurus has multiple prefLabels

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/DMA#4]
This is not a bug: more like an observation.

According to [Object Material](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_14-search_0) mapping, it maps to
```ttl
<http://data.americanartcollaborative.org/dma/object/3041171>
  crm:P45_consists_of <http://data.americanartcollaborative.org/dma/thesauri/material/oiloncanvas>.
<http://data.americanartcollaborative.org/dma/thesauri/material/oiloncanvas> a crm:E57_Material;
  skos:prefLabel "Oil on canvas".
```

If you examine http://data.americanartcollaborative.org/dma/thesauri/material/oiloncanvas, you'll find 4 prefLabels. According to SKOS, there should be 1 prefLabel.
3 of them look the same (but a couple have trailing spaces), one has a difference in capitalization. This query shows them explicitly and does some tests: http://yasgui.org/short/BydbnzI9g:
```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select ?g (concat("|",?y,"|") as ?z) (strlen(?y) as ?l) (?y="Oil on canvas " as ?b) { 
  graph ?g {
   <http://data.americanartcollaborative.org/dma/thesauri/material/oiloncanvas> skos:prefLabel ?y
  }
} 
```
For the life of me, I can't figure out what's different between the last two.

This smushing of prefLabels is a result of forming the URL by dropping spaces. It's the best that can be done, given that the museum doesn't have a proper thesaurus of materials.

Maybe one enhancement: normalize label spaces by dropping leading/trailing spaces, and reducing multiple internal spaces to a single one. (the XML type NMTOKENS does the same)

**Comment by vinayraod** [comment]
I removed the extra spaces in the terms.

**Comment by bsnikhila** [comment]
I removed the extra spaces.

**Comment by VladimirAlexiev** [comment]
Now has only 2 labels
