### ISSUE TITLE
Strange URI

### ISSUE THREAD

**Issue by workergnome** [american-art/DMA#5]
http://data.americanartcollaborative.org/page/dma/constituent/

This doesn't appear to be a real person...

**Comment by bmacelhose** [comment]
Who is the constituent in question? When I click the link, I do not see any names. I am still wrapping my head around all this so maybe I am just missing something.

**Comment by workergnome** [comment]
Dunno.  I would _guess_ that somewhere in the mappings there's a typo that maps some data to the constitutent, but forgot to append the ID to the URI.

**Comment by vinayraod** [comment]
Fixed it.

**Comment by bsnikhila** [comment]
Fixed it.
