### ISSUE TITLE
Death year of 0 seems wrong.

### ISSUE THREAD

**Issue by workergnome** [american-art/DMA#6]
For example, http://data.americanartcollaborative.org/page/dma/constituent/chavez_edward appears to have died in 0 AD.  This seems unlikely, since he was born in 1917.  I'm betting that 0 is an indicator of a null value.

**Comment by bmacelhose** [comment]
Yes, zero is the default value for the begin and end search dates in TMS.  That column is a (int, not null).

**Comment by workergnome** [comment]
@bmacelhose:  Would you like those mapped as zero, or would you like them to be excluded from the data?

If they're mapped as is, it would appear in the data as:

<img width="590" alt="screen shot 2017-03-23 at 2 54 55 pm" src="https://cloud.githubusercontent.com/assets/34536/24265083/b5cd16a4-0fd8-11e7-91ae-d194a48ae9ee.png">

**Comment by bmacelhose** [comment]
Gosh, I don't know... I would say do whatever will work best with respect to the functionality of searching by date as this is one of the key functions of this type of data field. Humans should be able to comprehend what zero means in the case. I am more concerned about the computer's comprehension here.

**Comment by bsnikhila** [comment]
I changed it to: If the death year is 0, there is no death class.

**Comment by workergnome** [comment]
Confirmed.  Thank you.
