### ISSUE TITLE
Gender uses blank nodes in type

### ISSUE THREAD

**Issue by workergnome** [american-art/DMA#7]
See, for instance, http://data.americanartcollaborative.org/page/dma/constituent/benjamin_west/gender.

Please replace with the actual type.

**Comment by bmacelhose** [comment]
Is there an action that I need to take here? If so, I am not sure what it is that I am supposed to do.  Sorry about my naivete on this...

**Comment by workergnome** [comment]
Nope--this is a Karma mapping issue, not a data issue, as far as I can tell.

**Comment by bsnikhila** [comment]
Plase let me know if this is alright
http://data.americanartcollaborative.org/page/dma/constituent/benjamin_west

**Comment by workergnome** [comment]
It matches the model.  (on further review, I don't love the model, but let's not change it mid-stream.)

Thank you.
